import os
from dotenv import load_dotenv

load_dotenv(verbose=True)

OCI_TARGET_COMPARTMENT_ID = os.getenv('OCI_TARGET_COMPARTMENT_ID')
OCI_OBJECTSTORAGE_BUCKET_NAME = os.getenv('OCI_OBJECTSTORAGE_BUCKET_NAME')
OCI_OBJECTSTORAGE_BUCKET_NAMESPCE = os.getenv('OCI_OBJECTSTORAGE_BUCKET_NAMESPCE')