# Generated by Django 4.2.7 on 2023-11-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oci_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_language_code', models.CharField(max_length=8)),
                ('result_content', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language_code', models.CharField(max_length=8)),
                ('target_content', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
