# Generated by Django 4.2.7 on 2023-11-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oci_ai', '0003_rename_after_content_translatehistory_aftercontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatehistory',
            options={},
        ),
    ]
