# Generated by Django 4.2.7 on 2023-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oci_ai', '0004_alter_translatehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatehistory',
            name='userAppVersion',
            field=models.CharField(max_length=10),
        ),
    ]
