# Generated by Django 4.2.7 on 2023-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oci_ai', '0006_statetranscribe_targettranscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('thumbnailUrl', models.TextField()),
                ('title', models.TextField()),
                ('like_cnt', models.IntegerField(default=0)),
                ('dislike_cnt', models.IntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
